import ChakraWrapper from "./Components/ChakraWrapper"
import Footer from "./Components/Footer"
import Header from "./Components/Header"

export const metadata = {
  title: 'Panaverse Website Awais Clone',
  description: 'Generated by Abdul Khaliq',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
      <ChakraWrapper>
      <Header />
      {children}
      <Footer />
      </ChakraWrapper>
      </body>
    </html>
  )
}
